# Generated by Django 5.1.2 on 2024-10-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Ticker', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Valor', models.IntegerField()),
                ('Fecha_Actual', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
